### ISSUE TITLE
New Button style

### ISSUE THREAD

**Issue by braaar** [indivorg/theme#12]
<img width="467" alt="Screenshot 2021-09-09 at 10 06 29" src="https://user-images.githubusercontent.com/5765650/132639015-67995774-d3e2-47e0-9409-4e6da1c65ad2.png">

```ts
{
  color: 'secondary',
  borderRadius: '8px',
}
```

**Comment by cobraz** [comment]
@braaar Should we remove the old primary and replace it with these?

**Comment by braaar** [comment]
> @braaar Should we remove the old primary and replace it with these?

Yeah, we should probably clarify in the design and elsewhere which buttons are the ones we actually need and such.

I sketched out these yesterday when I was working on theming the buttons: 

```ts
    create: {
      backgroundColor: 'lightGreen',
      color: 'text',
      borderRadius: '8px',
      cursor: 'pointer',
    },
    download: {
      backgroundColor: 'lightYellow',
      color: 'text',
      borderRadius: '8px',
      cursor: 'pointer',
    },
    danger: {
      backgroundColor: 'lightRed',
      color: 'text',
      borderRadius: '8px',
      cursor: 'pointer',
    },
```

**Comment by braaar** [comment]
Also added this colour from the design
```ts
lightYellow: '#FFE3B4',
```

**Comment by cobraz** [comment]
> ```ts
>     create: {
>       backgroundColor: 'lightGreen',
>       color: 'text',
>       borderRadius: '8px',
>       cursor: 'pointer',
>     },
>     download: {
>       backgroundColor: 'lightYellow',
>       color: 'text',
>       borderRadius: '8px',
>       cursor: 'pointer',
>     },
>     danger: {
>       backgroundColor: 'lightRed',
>       color: 'text',
>       borderRadius: '8px',
>       cursor: 'pointer',
>     },
> ```

Maybe we should use colour names/defaults? e.g. 

- success
- info
- warn

There are a few Theme UI themes that use this flow, see tailwind: https://github.com/system-ui/theme-ui/blob/a0be5f45d5994edeb161da7f0d715cd19e7347e9/packages/preset-tailwind/src/index.ts#L250-L256

**Comment by cobraz** [comment]
How about these colours?

- text (#0A1026)
- background (#fff)
- primary (#004D3F)
- secondary (#749F97)
- accent (#F9B644)
- muted (#F0F4F3)
- red (#E96565)
- lightGray (#F7FBFA)
- lightRed (#FFC7C7)
- lightGreen (#C5E7E0)
- success (#F7FBFA)
- warn (#FFC7C7)
- danger (#E96565)
