### ISSUE TITLE
React Native/Dripsy support

### ISSUE THREAD

**Issue by cobraz** [indivorg/theme#17]
We probably want to support React Native / Dripsy. There are styling that aren't available/supported by React Native / Dripsy, like `&:focus` doesn't work and will fail.

IMHO, we should have a streamlined theme that can be used on both mobile and web. But we might need to adjust specifically for platforms, e.g. web. This could be done like this:

```typescript
const webTheme = deepMerge(
  {
    buttons: {
      "&:focus": { // Specific for web
        borderColor: "secondary",
      },
    },
  },
  theme // But we inherit all from the common theme
);
```

The platforms could import the correct one like this:

```typescript
import { theme } from '@indivorg/theme'; // streamlined
import { webTheme } from '@indivorg/theme'; // for web
import { mobileTheme } from '@indivorg/theme'; // for mobile
```

**Note**: Even though I showcased having a separate file for mobile and web, I don't necessarily know if it's nice to have a separate one before it's _needed_. 🤷‍♂️

**Comment by cobraz** [comment]
> Does react native throw errors or misbehave if an unsupported style is applied?

Unfortunately, yes.

> Or is it possible to handle this issue by writing the styles in a clever way that lets us fall back onto other styles within the same theme?

I don't know how we can fall back to anything, unfortunately.

**Comment by braaar** [comment]
> Read more about radii here: https://theme-ui.com/theme-spec
Nice!

I suppose we can ditch the unsupported attribute for now and diverge the theme once we start the mobile development for real?

**Comment by cobraz** [comment]
IMHO, these are two efforts. 1) separate platform-specific stuff 2) improve/clean the theme.

**Comment by cobraz** [comment]
Created a separate issue for the `px` thing #19.
