### ISSUE TITLE
Scrollbar width issue

### ISSUE THREAD

**Issue by cobraz** [indivorg/theme#41]
_Moved here from indivorg/app#719._

From @braaar:
> Under the settings page, there is a noticeable "jump" when swapping between subunit settings and general settings since one of the pages features a scrollbar and the other doesn't (on a 108p screen at least)

**Comment by braaar** [comment]
Is [this suggestion from stackoverflow](https://stackoverflow.com/questions/1417934/how-to-prevent-scrollbar-from-repositioning-web-page) the solution we want to go for?

> overflow-y:scroll is correct, but you should use it with the html tag, not body or else you get a double scrollbar in IE 7
So the correct css would be:

```
html {
  overflow-y: scroll;
}
```

**Comment by cobraz** [comment]
> Is [this suggestion from stackoverflow](https://stackoverflow.com/questions/1417934/how-to-prevent-scrollbar-from-repositioning-web-page) the solution we want to go for?
> 
> > overflow-y:scroll is correct, but you should use it with the html tag, not body or else you get a double scrollbar in IE 7
> > So the correct css would be:
> 
> ```
> html {
>   overflow-y: scroll;
> }
> ```

Don't think so. I don't believe our issue is having two scrollbars.

**Comment by braaar** [comment]
I have a different fix that's working. PR coming.

**Comment by cobraz** [comment]
I did some research: I'm wrong, `overflow-y: scroll;` should be good!

**Comment by braaar** [comment]
I tested `overflow-y` and got double scroll bars

**Comment by braaar** [comment]
The testing was a bit sketchy though. I modified a `.js` file in `node_modules` to do it.

**Comment by braaar** [comment]
```js
import merge from 'ts-deepmerge';
import { theme } from '../theme';
export const webTheme = merge(theme, {
    buttons: {
        primary: {
            '&:focus': {
                borderColor: 'secondary',
            },
        },
    },
    styles: {
        root: {
            '-webkit-font-smoothing': 'antialiased',
            '-moz-osx-font-smoothing': 'grayscale',
            'overflow-y':'scroll',
        },
    },
});
```
![Screenshot 2021-11-23 at 18 24 28](https://user-images.githubusercontent.com/5765650/143063433-341b01d0-78ab-4fd5-b478-20b1402df56e.png)
